
version: "2"

services:
  
  postgres:
    image: postgres:9.4.5
    ports: "5432:5432"
    environment:
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: yourpassword
    volumes:
      - postgres-copy:/var/lib/postgresql/data

  redis:
    image: redis:3.0.5
    ports: "6379:6379"
    volumes:
      - redis-copy:/var/lib/redis/data

  todo:
    build: . #path to the Dockerfile
    links:
      - postgress
      - redis
    volumes:
      - .:/todo
    ports: "3000:3000"
    env_file: .todo.env

  volumes:
    postgres-copy
    redis-copy

    

    
