# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.box_check_update = false
  config.vm.define "host"
  config.vm.hostname = "rubyserver"
  
  # Forward the default HTTP port of the built in rails development server.
  config.vm.network "forwarded_port", guest: 3000, host: 3000

  
  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"
  
  config.vm.provider "virtualbox" do |vb|
  # Customize the amount of memory on the VM:
     vb.memory = "2048"
  end

  #http://foo-o-rama.com/vagrant--stdin-is-not-a-tty--fix.html
  #config.vm.provision "fix-no-tty", type: "shell" do |s|
  #  s.privileged = false
   # s.inline = "sudo sed -i '/tty/!s/mesg n/tty -s \\&\\& mesg n/' /root/.profile"
  #end
  
  config.vm.provision :shell, path: "ruby.sh", privileged: false
  config.vm.provision :shell, path: "app.sh", privileged: false
  
 
end
